mindmap
  root((ubuntu))
    OpenWebui, Light Webui
      local
      web-on-demand
      agent-online/offline
    ollama
      specific models
      reusing gpt4ll models
    gpt4all
      local models
      local history
      local knowledge base
    python alignment components

