journey
    title Morning reading
    section Go to work
      Look at websites: 3: Me
      Read selection: 5: Me
      Post on Twitter: 3: Me
    section Working day
      Run to the first meeting: 5: Me
      ...: 20: Many
      Go to the bus stop: 3: Me

